# Generated by Django 5.1.7 on 2025-03-25 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientCompanie',
            new_name='ClientCompany',
        ),
    ]
